### ISSUE TITLE
Support for adding callbacks

### ISSUE THREAD

**Issue by Jefftree** [Yelp/fido#51]
I sometimes find myself wanting to use the callback approach instead of calling `future.wait()`. Would it be possible to add this feature for fido?

**Comment by lucagiovagnoli** [comment]
Actually that is exactly what fido does not want to be. What you are suggesting means building a callback API that eventually will just replicate the underlying Twisted API (i.e. we will have callbacks, errbacks etc.). I would argue we could just use Twisted directly at that point. 

Also **most importantly**, Fido uses crochet. From [crochet page](https://github.com/itamarst/crochet): "[...] a library that provides a blocking API, but uses Twisted for its implementation."
Fido solves the problem of callback hell and provides a clean blocking API making writing async code easy as writing synchronous.

In the past we had a parallel internal project which was built with callbacks in mind. Eventually we decided to move forward with this fido's paradigm. I can link you more material offline, closing this for now.
