### ISSUE TITLE
fido does not support underscores in domain name

### ISSUE THREAD

**Issue by jangsutsr** [Yelp/fido#58]
```
>>> future = fido.fetch('https://i_have_underscores.com/path')
>>> print(future.wait(timeout=2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nail/home/siruitan/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/crochet/_eventloop.py", line 231, in wait
    result.raiseException()
  File "<string>", line 2, in raiseException
idna.core.InvalidCodepoint: Codepoint U+005F at position 5 of u'fake_platform_partner-testopia' not allowed
```

Please help, this issue breaks a non-trivial number of our integrated tests.

**Comment by sjaensch** [comment]
_ is not a valid character for a hostname. Where are these coming from? As you can see from the exception, it is not thrown by fido, but by a lower level library that deals with (possibly internationalized) URLs. There is nothing fido can do here; you'll need to change the host names. One thing Paasta does when auto-generating host names is converting underscores to hyphens.
